version: "3.3"
services:
  db:
    image: mysql:5.7.22
    container_name: db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: covid
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    expose:
      - 3308
    volumes:
      - .:/app

  backend:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: gunicorn --bind 0.0.0.0:8000 app:app
    environment:
      - SQLALCHEMY_DATABASE_URI=mysql+mysqldb://root:root@db:8000/covid
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    restart: always






